- name: variables
  hosts: local
  connection: local 
  vars: 
    COURSE: "Devops with AWS"
    DURATION: 120hrs
    TRAINER: "Siva reddy"
  tasks:
  - name: Print variable1
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
  - name: Print variable2
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"