- name: variable
  hosts: local
  connection: local 
  tasks:
  vars: 
    COURSE: "Devops with AWS"
    DURATION: 120hrs
    TRAINER: "Siva reddy"
  - name: Print variable
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer {{ TRAINER }}"