- name: variables
  hosts: local
  connection: local
  vars:
    GREET: "Play"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: GREET
    prompt: Enter the value
    private: false
  tasks:
  - name: Print course information
    vars:
      GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"