- name: instal nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx if RHEL
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: anible_os_family == "RedHat"

   - name: install nginx if UBUNTU
     ansible.builtin.apt:  
       name: nginx
       state: installed
     when: anible_os_family == "Debian"  