- name: install package
  hosts: web
  become: yes
  tasks:
  - name: install the package
    ansible.builtin.package:
      name: "{{ item }}"
      state: 
    loop:
    - gcc
    - mysql
    - git
    - zip 