- name: Intall Package
  hosts: web
  become: yes
  tasks:
  - name: Install packages one by one
    ansible.builtiin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - "{{ name: 'git', state: present }}"
    - "{{ name: 'mysql', state: absent }}"
    - "{{ name: 'gcc', state: present }}"
    - "{{ name: 'zip', state: absent }}"