- name: filters
  hosts: local 
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('ramesh') }}"

  - name: convert string to list
    vars:
      fruits: "apple, banana, Java"
    ansible.builtin.debug:
      msg: " Fruits are: {{ fruits | split(',') }} "

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: sivareddy
    ansible.builtin.debug:
      msg: " course info is {{ course | dict2items }} "
    
  - name: convert list to map
    vars:
      course:
       - {'key': 'name', 'value': 'ansible'} 
       - {'key': 'duration', 'value': '10hrs'}
       - {'key': 'trainer', 'value': 'sivareddy'}
    ansible.builtin.debug:
      msg: " course info is {{ course | items2dict }} "

  - name: convert upper to lower
    vars:
      name: " Siva Kumar Reddy"
    ansible.built.debug:
      msg: " Hello {{ name | lower }} "