- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: execure ls command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: execute the ls command in command module
    ansible.builtin.command: lsss -ltrrr
    register: command_result

  - name: Print the output
    ansible.builtin.debug:
      msg: "{{ command_result }}"